// Storyboard for the stash guide. Every command is real; the check script replays them in order against a repository.
export type StashStep = { title: string; command: string; output: string; explanation: string; file: string[]; head: string; stashes: string[]; status: string; conflict?: boolean };

export const stashCommits: Record<string, { message: string; lines: string[] }> = {
  B: { message: "Add The Hobbit", lines: ["# Reading list", "- Dune", "- The Hobbit"] },
  C: { message: "Fix the title", lines: ["# Books to read", "- Dune", "- The Hobbit"] },
  D: { message: "Add Piranesi", lines: ["# Books to read", "- Dune", "- The Hobbit", "- Piranesi"] },
};
const { B, C, D } = stashCommits;
export const stashConflictNotes: Record<number, string> = { 3: "main’s side starts", 4: "what main has", 5: "divider", 6: "what the entry has", 7: "entry’s side ends" };

const applied = 'On branch main\nChanges not staged for commit:\n  (use "git add <file>..." to update what will be committed)\n  (use "git restore <file>..." to discard changes in working directory)\n\tmodified:   reading-list.md\n\nno changes added to commit (use "git add" and/or "git commit -a")';
const twoEntries = ["stash@{0}: On main: Add Foundation", "stash@{1}: On main: Add Piranesi"];

export const stashSteps: StashStep[] = [
  { title: "Halfway through a change", command: "git status --short", output: " M reading-list.md", explanation: "You added Piranesi to the list and have not staged or committed it. Sam asks for a quick fix to the title. You do not want your half-done line in that commit.", file: [...B.lines, "- Piranesi"], head: "B", stashes: [], status: " M reading-list.md" },
  { title: "Put it on the shelf", command: 'git stash push -m "Add Piranesi"', output: "Saved working directory and index state On main: Add Piranesi", explanation: "Git records your working file and staging area as an entry, then resets both to the last commit. The file on disk no longer has Piranesi; the entry does. The working tree is clean.", file: B.lines, head: "B", stashes: ["stash@{0}: On main: Add Piranesi"], status: "" },
  { title: "Shelve a second change", command: 'printf "%s\\n" "- Foundation" >> reading-list.md\ngit stash push -m "Add Foundation"', output: "Saved working directory and index state On main: Add Foundation", explanation: "Another half-done change, shelved the same way. Both entries were recorded against the same commit, B. That detail matters later.", file: B.lines, head: "B", stashes: twoEntries, status: "" },
  { title: "Read the shelf", command: "git stash list", output: twoEntries.join("\n"), explanation: "Newest first. stash@{0} is always the most recent entry, so Add Piranesi moved from 0 to 1 when Add Foundation arrived. The message you gave with -m is what tells them apart.", file: B.lines, head: "B", stashes: twoEntries, status: "" },
  { title: "Do the urgent fix", command: 'printf "# Books to read\\n- Dune\\n- The Hobbit\\n" > reading-list.md\ngit commit -am "Fix the title"', output: "[main 22cb301] Fix the title\n 1 file changed, 1 insertion(+), 1 deletion(-)", explanation: "With a clean working tree, the fix is an ordinary commit, C. Neither entry changes: both still describe a change against B, and main has moved on.", file: C.lines, head: "C", stashes: twoEntries, status: "" },
  { title: "Look before you take", command: "git stash show 1", output: " reading-list.md | 1 +\n 1 file changed, 1 insertion(+)", explanation: "show summarizes what an entry would change; add -p for the full patch. The number 1 is short for stash@{1}.", file: C.lines, head: "C", stashes: twoEntries, status: "" },
  { title: "Apply the older entry", command: "git stash apply 1", output: `Auto-merging reading-list.md\n${applied}`, explanation: "apply merges the entry into your current file. The title fix and the Piranesi line are far apart, so it goes cleanly. The change is back as an unstaged edit, and the entry is still on the shelf: apply never removes anything.", file: [...C.lines, "- Piranesi"], head: "C", stashes: twoEntries, status: " M reading-list.md" },
  { title: "Commit it, then drop the entry", command: 'git commit -am "Add Piranesi"\ngit stash drop 1', output: "[main c39b345] Add Piranesi\n 1 file changed, 1 insertion(+)\nDropped refs/stash@{1} (5fcc4e0acd10bee65bb6bcaf76c79ff9c6551d4f)", explanation: "The change is recorded as D. Because you used apply, you remove the entry yourself. Only Add Foundation is left, and it is stash@{0} now.", file: D.lines, head: "D", stashes: [twoEntries[0]], status: "" },
  { title: "Pop the other one: it conflicts", command: "git stash pop", output: 'Auto-merging reading-list.md\nCONFLICT (content): Merge conflict in reading-list.md\nOn branch main\nUnmerged paths:\n  (use "git restore --staged <file>..." to unstage)\n  (use "git add <file>..." to mark resolution)\n\tboth modified:   reading-list.md\n\nno changes added to commit (use "git add" and/or "git commit -a")\nThe stash entry is kept in case you need it again.', explanation: "Add Foundation adds a line after The Hobbit. Since B, main added Piranesi in the same place, so Git cannot order them and stops with markers. pop drops an entry only after a clean apply, so the entry stays. Updated upstream is main’s side; Stashed changes is the entry’s.", file: [...D.lines.slice(0, 3), "<<<<<<< Updated upstream", "- Piranesi", "=======", "- Foundation", ">>>>>>> Stashed changes"], head: "D", stashes: [twoEntries[0]], status: "UU reading-list.md", conflict: true },
  { title: "Answer, stage, and drop it yourself", command: 'printf "# Books to read\\n- Dune\\n- The Hobbit\\n- Piranesi\\n- Foundation\\n" > reading-list.md\ngit add reading-list.md\ngit stash drop', output: "Dropped refs/stash@{0} (fc1956ab1437fe9b34ba1dc76802696d695d133e)", explanation: "Edit the file to the answer, as after any merge conflict, and stage it: add is what tells Git the conflict is resolved. Nothing is in progress and there is no stash --continue; commit when you are ready. The entry stayed on the shelf until you dropped it.", file: [...D.lines, "- Foundation"], head: "D", stashes: [], status: "M  reading-list.md" },
];
