// A label map: branch or remote-tracking name → commit letter.
export type ForkLabels = Record<string, string>;
export type ForkStep = { title: string; command: string; explanation: string; upstream: ForkLabels; fork: ForkLabels | null; laptop: ForkLabels | null; head: string | null; pr: "none" | "open" | "merged" };

export const forkCommits: Record<string, string> = { A: "Start the reading list", B: "Add The Hobbit", C: "Add Piranesi", M: "Merge pull request #1 from maya/add-piranesi" };

export const forkSteps: ForkStep[] = [
  { title: "Sam’s project", command: "sam/reading-list · on the service", explanation: "Sam owns the original repository. You can read it and clone it, but you cannot push to it.", upstream: { main: "B" }, fork: null, laptop: null, head: null, pr: "none" },
  { title: "Fork it", command: "On the service: Fork", explanation: "The service copies Sam’s repository under your account as maya/reading-list. A fork is a clone that lives on the service, and you can push to it.", upstream: { main: "B" }, fork: { main: "B" }, laptop: null, head: null, pr: "none" },
  { title: "Clone your fork", command: "git clone maya/reading-list.git laptop", explanation: "Your laptop gets a copy of the fork, not of Sam’s repository. origin means your fork, and main tracks origin/main.", upstream: { main: "B" }, fork: { main: "B" }, laptop: { main: "B", "origin/main": "B" }, head: "main", pr: "none" },
  { title: "Add the original as upstream", command: "git remote add upstream sam/reading-list.git\ngit fetch upstream", explanation: "A second remote, named upstream by convention, points at Sam’s repository. Fetching it gives you upstream/main: your record of Sam’s main.", upstream: { main: "B" }, fork: { main: "B" }, laptop: { main: "B", "origin/main": "B", "upstream/main": "B" }, head: "main", pr: "none" },
  { title: "Branch and commit", command: "git switch -c add-piranesi\ngit commit -am \"Add Piranesi\"", explanation: "Work on a branch named after the change, never on main. Only your laptop knows about C so far.", upstream: { main: "B" }, fork: { main: "B" }, laptop: { main: "B", "add-piranesi": "C", "origin/main": "B", "upstream/main": "B" }, head: "add-piranesi", pr: "none" },
  { title: "Push the branch to your fork", command: "git push -u origin add-piranesi", explanation: "The branch now exists on your fork too, and origin/add-piranesi records that. Nothing went to Sam’s repository; you could not push there anyway.", upstream: { main: "B" }, fork: { main: "B", "add-piranesi": "C" }, laptop: { main: "B", "add-piranesi": "C", "origin/main": "B", "origin/add-piranesi": "C", "upstream/main": "B" }, head: "add-piranesi", pr: "none" },
  { title: "Open the pull request", command: "On the service: New pull request · maya:add-piranesi → sam:main", explanation: "A pull request is a request to merge your fork’s branch into Sam’s main. It points at the branch, so no commit moves and nothing is copied. Sam reviews it there.", upstream: { main: "B" }, fork: { main: "B", "add-piranesi": "C" }, laptop: { main: "B", "add-piranesi": "C", "origin/main": "B", "origin/add-piranesi": "C", "upstream/main": "B" }, head: "add-piranesi", pr: "open" },
  { title: "Sam merges it", command: "On the service: Merge pull request", explanation: "Sam’s main moves to a merge commit M with parents B and C. Your fork and your laptop are unchanged: their main labels still say B.", upstream: { main: "M" }, fork: { main: "B", "add-piranesi": "C" }, laptop: { main: "B", "add-piranesi": "C", "origin/main": "B", "origin/add-piranesi": "C", "upstream/main": "B" }, head: "add-piranesi", pr: "merged" },
  { title: "Bring Sam’s main to your laptop", command: "git fetch upstream\ngit switch main\ngit merge --ff-only upstream/main", explanation: "Fetch updates upstream/main. Your main is at B, an ancestor of M, so the merge is a fast-forward: main slides to M.", upstream: { main: "M" }, fork: { main: "B", "add-piranesi": "C" }, laptop: { main: "M", "add-piranesi": "C", "origin/main": "B", "origin/add-piranesi": "C", "upstream/main": "M" }, head: "main", pr: "merged" },
  { title: "Bring it to your fork", command: "git push origin main", explanation: "Your fork does not follow Sam’s repository by itself. Pushing main moves the fork’s main and origin/main to M, so the three main labels agree again.", upstream: { main: "M" }, fork: { main: "M", "add-piranesi": "C" }, laptop: { main: "M", "add-piranesi": "C", "origin/main": "M", "origin/add-piranesi": "C", "upstream/main": "M" }, head: "main", pr: "merged" },
  { title: "Clean up", command: "git branch -d add-piranesi\ngit push origin --delete add-piranesi", explanation: "The branch did its job. Delete it locally and on the fork. C is still in history, as the second parent of M.", upstream: { main: "M" }, fork: { main: "M" }, laptop: { main: "M", "origin/main": "M", "upstream/main": "M" }, head: "main", pr: "merged" },
];

export function labelChanges(current: ForkLabels | null, previous: ForkLabels | null) {
  const rows = Object.entries(current ?? {}).map(([name, id]) => ({ name, id, note: !previous || !(name in previous) ? "new" : previous[name] !== id ? "moved" : "" }));
  const removed = Object.keys(previous ?? {}).filter(name => !(name in (current ?? {})));
  return { rows, removed };
}
